import * as fs from 'fs';
import * as NodePath from 'path';
import { VirtualFolder, VirtualFile } from './EIDETypeDefine';

//
// CMake project importer: parse `compile_commands.json` (generated by
// `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`) into a description eide can turn
// into a project (sources, include dirs, macros, toolchain family, arch).
//

export interface CmakeProjectInfo {
    name: string;
    // toolchain family, guessed from the compiler binary name
    type: 'arm' | 'riscv' | 'gcc';
    compiler: string;
    // sources grouped by directory (relative to rootDir)
    virtualSource: VirtualFolder;
    cIncDirs: string[];
    cMacros: string[];
    cCompilerArgs: string[];
    archName?: string;
    linkerScriptPath?: string;
    rootDir: string;
}

// minimal shell-like tokenizer (handles single/double quotes)
function tokenizeCommand(cmd: string): string[] {
    const tokens: string[] = [];
    let cur = '';
    let quote: string | null = null;
    for (let i = 0; i < cmd.length; i++) {
        const ch = cmd[i];
        if (quote) {
            if (ch === quote) {
                quote = null;
            } else {
                cur += ch;
            }
        } else if (ch === '"' || ch === '\'') {
            quote = ch;
        } else if (ch === ' ' || ch === '\t') {
            if (cur) { tokens.push(cur); cur = ''; }
        } else {
            cur += ch;
        }
    }
    if (cur) tokens.push(cur);
    return tokens;
}

function compilerBasename(cmd0: string): string {
    return NodePath.basename(cmd0).toLowerCase();
}

const ARCH_MAP: { [name: string]: string } = {
    'cortex-m0plus': 'Cortex-M0+', 'cortex-m0+': 'Cortex-M0+',
    'cortex-m0': 'Cortex-M0', 'cortex-m3': 'Cortex-M3',
    'cortex-m4': 'Cortex-M4', 'cortex-m7': 'Cortex-M7',
    'cortex-m23': 'Cortex-M23', 'cortex-m33': 'Cortex-M33',
    'cortex-m55': 'Cortex-M55', 'cortex-m85': 'Cortex-M85',
    'cortex-m35p': 'Cortex-M35P'
};

// build a nested VirtualFolder from a list of relative file paths
function buildVirtualFolder(name: string, relFiles: string[]): VirtualFolder {
    const root: VirtualFolder = { name, files: [], folders: [] };

    const ensureFolder = (folder: VirtualFolder, parts: string[], filePath: string) => {
        if (parts.length == 0) {
            folder.files.push(<VirtualFile>{ path: filePath });
            return;
        }
        const seg = parts[0];
        let child = folder.folders.find(f => f.name == seg);
        if (!child) {
            child = { name: seg, files: [], folders: [] };
            folder.folders.push(child);
        }
        ensureFolder(child, parts.slice(1), filePath);
    };

    for (const rel of relFiles) {
        const normalized = rel.replace(/\\/g, '/');
        const parts = normalized.split('/').filter(p => p && p != '.');
        // last part is the file name
        const dirParts = parts.slice(0, parts.length - 1);
        ensureFolder(root, dirParts, normalized);
    }

    return root;
}

export async function parseCompileCommands(jsonPath: string, projectRootDir?: string): Promise<CmakeProjectInfo> {

    const raw = fs.readFileSync(jsonPath, 'utf8');
    const entries: any[] = JSON.parse(raw);

    if (!Array.isArray(entries) || entries.length == 0) {
        throw new Error('compile_commands.json is empty or invalid');
    }

    // use first entry to detect compiler + toolchain family
    const first = entries[0];
    const firstTokens = tokenizeCommand(
        first.command || (Array.isArray(first.arguments) ? first.arguments.join(' ') : '')
    );
    const compiler = compilerBasename(firstTokens[0] || '');

    let type: 'arm' | 'riscv' | 'gcc';
    if (/arm-none-eabi|arm-eabi|arm-linux|armv[0-9]/.test(compiler)) type = 'arm';
    else if (/riscv/.test(compiler)) type = 'riscv';
    else type = 'gcc';

    // root dir is the CMakeLists.txt directory (project root); fallback to json dir
    const rootDir = projectRootDir || NodePath.dirname(jsonPath);

    const sources: string[] = [];
    const incSet = new Set<string>();
    const macroSet = new Set<string>();
    const argSet = new Set<string>();
    let archName: string | undefined;
    let linkerScriptPath: string | undefined;

    for (const entry of entries) {
        if (entry.file) {
            sources.push(entry.file);
        }
        const cmd = entry.command || (Array.isArray(entry.arguments) ? entry.arguments.join(' ') : '');
        const tk = tokenizeCommand(cmd);
        for (let i = 1; i < tk.length; i++) {
            const t = tk[i];
            if (t == '-I' || t.startsWith('-I')) {
                let p = t.length > 2 ? t.slice(2) : tk[++i];
                if (p) incSet.add(p);
            } else if (t == '-D' || t.startsWith('-D')) {
                let m = t.length > 2 ? t.slice(2) : tk[++i];
                if (m) macroSet.add(m);
            } else if (t.startsWith('-mcpu=') || t.startsWith('-march=')) {
                const arch = t.split('=')[1];
                if (arch) archName = arch;
            } else if (t == '-T' || t.startsWith('-T')) {
                let p = t.length > 2 ? t.slice(2) : tk[++i];
                if (p) linkerScriptPath = p;
            } else if (t == '-c' || t == '-o' || t == '-MF' || t == '-MT' || t == '-MQ'
                || t.startsWith('-o') || t.startsWith('-MF') || t.startsWith('-MT') || t.startsWith('-MQ')) {
                // skip output/dependency args (may have a following value)
                if (t == '-c' || t == '-o' || t == '-MF' || t == '-MT' || t == '-MQ') i++;
            } else if (!t.startsWith('-o') && !t.endsWith('.o') && !t.endsWith('.c') && !t.endsWith('.cpp')
                && !t.endsWith('.cc') && !t.endsWith('.cxx') && !t.endsWith('.s') && !t.endsWith('.S')) {
                // collect remaining flags as generic compiler args
                if (t.startsWith('-')) argSet.add(t);
            }
        }
    }

    // make include dirs relative where possible
    const cIncDirs = Array.from(incSet).map(p => {
        if (NodePath.isAbsolute(p)) {
            const rel = NodePath.relative(rootDir, p);
            if (!rel.startsWith('..') && rel != '') return rel;
            return p;
        }
        return p;
    });

    // relative source paths for virtual folder
    const relSources = Array.from(new Set(sources)).map(p => {
        if (NodePath.isAbsolute(p)) {
            const rel = NodePath.relative(rootDir, p);
            return rel.startsWith('..') ? p : rel;
        }
        return p;
    });

    return {
        name: NodePath.basename(rootDir),
        type,
        compiler,
        virtualSource: buildVirtualFolder('Sources', relSources),
        cIncDirs,
        cMacros: Array.from(macroSet),
        cCompilerArgs: Array.from(argSet),
        archName: archName ? (ARCH_MAP[archName.toLowerCase()] || archName) : undefined,
        linkerScriptPath,
        rootDir
    };
}

//
// locate compile_commands.json under a CMake project root.
// searches: <root>/build/compile_commands.json, <root>/compile_commands.json,
// then a shallow recursive scan (depth 3) for any compile_commands.json.
//
export function findCompileCommands(rootDir: string): string | undefined {

    const candidates = [
        NodePath.join(rootDir, 'build', 'compile_commands.json'),
        NodePath.join(rootDir, 'compile_commands.json'),
    ];
    for (const p of candidates) {
        if (fs.existsSync(p)) return p;
    }

    // shallow recursive scan (depth-limited to avoid scanning the whole tree)
    const scan = (dir: string, depth: number): string | undefined => {
        if (depth > 3) return undefined;
        let entries: string[] = [];
        try {
            entries = fs.readdirSync(dir);
        } catch (e) {
            return undefined;
        }
        for (const name of entries) {
            const full = NodePath.join(dir, name);
            let st: any;
            try { st = fs.statSync(full); } catch (e) { continue; }
            if (st.isDirectory()) {
                if (/node_modules|\.git|\.svn/i.test(name)) continue;
                const hit = scan(full, depth + 1);
                if (hit) return hit;
            } else if (name == 'compile_commands.json') {
                return full;
            }
        }
        return undefined;
    };

    return scan(rootDir, 0);
}

//
// extract POST_BUILD commands from a CMake project, following include() chains
// (e.g. CMakeLists.txt -> include(post_build) -> cmake/post_build.cmake with
// add_custom_command(TARGET ... POST_BUILD ...)). Resolves common CMake
// variables into eide builtin variables.
//
function resolveCmakeVars(cmd: string, toolchainPrefix?: string): string {
    // $<TARGET_FILE:xxx> -> eide output elf path
    cmd = cmd.replace(/\$<TARGET_FILE:[^>]+>/g, '${OutDir}/${ProjectName}.elf');
    // $<TARGET_FILE_DIR:xxx> -> output dir
    cmd = cmd.replace(/\$<TARGET_FILE_DIR:[^>]+>/g, '${OutDir}');
    // ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} -> output dir
    cmd = cmd.replace(/\$\{CMAKE_RUNTIME_OUTPUT_DIRECTORY\}/g, '${OutDir}');
    // ${CMAKE_BINARY_DIR} / ${CMAKE_CURRENT_BINARY_DIR} -> build dir
    cmd = cmd.replace(/\$\{CMAKE_BINARY_DIR\}/g, '${OutDir}');
    cmd = cmd.replace(/\$\{CMAKE_CURRENT_BINARY_DIR\}/g, '${OutDir}');
    // ${CMAKE_SOURCE_DIR} / ${CMAKE_CURRENT_SOURCE_DIR} -> project root
    cmd = cmd.replace(/\$\{CMAKE_SOURCE_DIR\}/g, '${ProjectRoot}');
    cmd = cmd.replace(/\$\{CMAKE_CURRENT_SOURCE_DIR\}/g, '${ProjectRoot}');
    // ${CMAKE_COMMAND} -> cmake
    cmd = cmd.replace(/\$\{CMAKE_COMMAND\}/g, 'cmake');
    // ${PROJECT_NAME} -> eide project name
    cmd = cmd.replace(/\$\{PROJECT_NAME\}/g, '${ProjectName}');
    // toolchain binutils
    if (toolchainPrefix) {
        cmd = cmd.replace(/\$\{CMAKE_OBJCOPY\}/g, toolchainPrefix + 'objcopy');
        cmd = cmd.replace(/\$\{CMAKE_SIZE\}/g, toolchainPrefix + 'size');
        cmd = cmd.replace(/\$\{CMAKE_OBJDUMP\}/g, toolchainPrefix + 'objdump');
        cmd = cmd.replace(/\$\{CMAKE_RANLIB\}/g, toolchainPrefix + 'ranlib');
    }
    return cmd;
}

export function parseCmakePostBuild(cmakeListsPath: string, toolchainPrefix?: string): { name: string, command: string }[] {

    const rootDir = NodePath.dirname(cmakeListsPath);
    const tasks: { name: string, command: string }[] = [];
    const visited = new Set<string>();

    const collectFromFile = (filePath: string) => {
        const abs = NodePath.resolve(filePath);
        if (visited.has(abs)) return;
        visited.add(abs);

        let content: string;
        try {
            content = fs.readFileSync(abs, 'utf8');
        } catch (e) {
            return;
        }

        // add_custom_command(TARGET ... POST_BUILD ...) blocks
        const re = /add_custom_command\s*\(\s*TARGET\s+[^\s]+\s+POST_BUILD([\s\S]*?)\)/g;
        let m: RegExpExecArray | null;
        while ((m = re.exec(content))) {
            const block = m[1];
            // split by COMMAND keyword; each segment after the first is one command
            const parts = block.split(/\bCOMMAND\b/);
            for (let i = 1; i < parts.length; i++) {
                // cut at trailing add_custom_command keywords (COMMENT/VERBATIM/...)
                const seg = parts[i].split(/\s+(?:COMMENT|VERBATIM|WORKING_DIRECTORY|DEPENDS|BYPRODUCTS|MAIN_DEPENDENCY)\b/)[0];
                let cmd = seg.trim().replace(/\s+/g, ' ');
                if (!cmd) continue;
                cmd = resolveCmakeVars(cmd, toolchainPrefix);
                tasks.push({ name: cmd, command: cmd });
            }
        }

        // follow include() chains
        const incRe = /include\s*\(\s*([A-Za-z0-9_.-]+)\s*\)/g;
        let im: RegExpExecArray | null;
        while ((im = incRe.exec(content))) {
            const incName = im[1];
            const candidates = [
                NodePath.join(rootDir, 'cmake', incName + '.cmake'),
                NodePath.join(rootDir, incName + '.cmake'),
                NodePath.join(rootDir, incName),
            ];
            for (const c of candidates) {
                if (fs.existsSync(c)) {
                    collectFromFile(c);
                    break;
                }
            }
        }
    };

    collectFromFile(cmakeListsPath);
    return tasks;
}

//
// parse linker config from a CMake project (following include() chains):
// linker script path (set(LINKER_SCRIPT_NAME/DIR) or -Txxx.ld), RISC-V arch/abi
// (set(RISCV_ARCH/RISCV_ABI) or -march/-mabi).
//
export interface CmakeLinkConfig {
    linkerScriptPath?: string;
    arch?: string;
    abi?: string;
}

export function parseCmakeLinkConfig(cmakeListsPath: string): CmakeLinkConfig {

    const rootDir = NodePath.dirname(cmakeListsPath);
    const result: CmakeLinkConfig = {};
    const visited = new Set<string>();

    const collect = (filePath: string) => {
        const abs = NodePath.resolve(filePath);
        if (visited.has(abs)) return;
        visited.add(abs);

        let content: string;
        try {
            content = fs.readFileSync(abs, 'utf8');
        } catch (e) {
            return;
        }

        // linker script: set(LINKER_SCRIPT_NAME xxx.ld) + set(LINKER_SCRIPT_DIR ...)
        if (!result.linkerScriptPath) {
            const nm = /set\s*\(\s*LINKER_SCRIPT_NAME\s+([^\s)]+)/.exec(content);
            if (nm) {
                const name = nm[1].replace(/["']/g, '');
                let dir = '';
                const dm = /set\s*\(\s*LINKER_SCRIPT_DIR\s+([^\s)]+)/.exec(content);
                if (dm) {
                    const raw = dm[1].replace(/["']/g, '');
                    // ${CMAKE_CURRENT_SOURCE_DIR}/icf -> icf
                    dir = raw.replace(/\$\{[^}]+\}/g, '').replace(/^\/+/, '');
                }
                result.linkerScriptPath = dir ? `${dir}/${name}` : name;
            }
        }

        // arch/abi
        let m = /set\s*\(\s*RISCV_ARCH\s+["']?([^"'\s)]+)/.exec(content);
        if (m && !result.arch) result.arch = m[1];
        m = /set\s*\(\s*RISCV_ABI\s+["']?([^"'\s)]+)/.exec(content);
        if (m && !result.abi) result.abi = m[1];

        // fallback: -march=xxx / -mabi=xxx in link/compile flags
        if (!result.arch) {
            m = /-march=([^\s]+)/.exec(content);
            if (m) result.arch = m[1];
        }
        if (!result.abi) {
            m = /-mabi=([^\s]+)/.exec(content);
            if (m) result.abi = m[1];
        }

        // follow include() chains
        const incRe = /include\s*\(\s*([A-Za-z0-9_.-]+)\s*\)/g;
        let im: RegExpExecArray | null;
        while ((im = incRe.exec(content))) {
            const incName = im[1];
            const candidates = [
                NodePath.join(rootDir, 'cmake', incName + '.cmake'),
                NodePath.join(rootDir, incName + '.cmake'),
                NodePath.join(rootDir, incName),
            ];
            for (const c of candidates) {
                if (fs.existsSync(c)) {
                    collect(c);
                    break;
                }
            }
        }
    };

    collect(cmakeListsPath);
    return result;
}

//
// extract PRE-build commands from a CMake project (add_custom_target(... ALL
// COMMAND ...) + add_dependencies), following include() chains. e.g.
// add_custom_target(sync_revision ALL COMMAND cmd /c ".../SyncRevision.bat" ...)
//
export function parseCmakePreBuild(cmakeListsPath: string): { name: string, command: string }[] {

    const rootDir = NodePath.dirname(cmakeListsPath);
    const tasks: { name: string, command: string }[] = [];
    const visited = new Set<string>();

    const collectFromFile = (filePath: string) => {
        const abs = NodePath.resolve(filePath);
        if (visited.has(abs)) return;
        visited.add(abs);

        let content: string;
        try {
            content = fs.readFileSync(abs, 'utf8');
        } catch (e) {
            return;
        }

        // add_custom_target(name [ALL] ... COMMAND ...) blocks
        const re = /add_custom_target\s*\(\s*[^\s]+\s+(?:ALL\s+)?([\s\S]*?)\)/g;
        let m: RegExpExecArray | null;
        while ((m = re.exec(content))) {
            const block = m[1];
            const parts = block.split(/\bCOMMAND\b/);
            for (let i = 1; i < parts.length; i++) {
                const seg = parts[i].split(/\s+(?:COMMENT|VERBATIM|WORKING_DIRECTORY|DEPENDS|BYPRODUCTS)\b/)[0];
                let cmd = seg.trim().replace(/\s+/g, ' ');
                if (!cmd) continue;
                // skip commands targeting other host platforms (if(CMAKE_HOST_WIN32) branches)
                const isWin = process.platform === 'win32';
                if (isWin && /\.sh\b/.test(cmd)) continue;
                if (!isWin && /\.bat\b/.test(cmd)) continue;
                cmd = resolveCmakeVars(cmd);
                tasks.push({ name: cmd, command: cmd });
            }
        }

        // follow include() chains
        const incRe = /include\s*\(\s*([A-Za-z0-9_.-]+)\s*\)/g;
        let im: RegExpExecArray | null;
        while ((im = incRe.exec(content))) {
            const incName = im[1];
            const candidates = [
                NodePath.join(rootDir, 'cmake', incName + '.cmake'),
                NodePath.join(rootDir, incName + '.cmake'),
                NodePath.join(rootDir, incName),
            ];
            for (const c of candidates) {
                if (fs.existsSync(c)) {
                    collectFromFile(c);
                    break;
                }
            }
        }
    };

    collectFromFile(cmakeListsPath);
    return tasks;
}
